### ISSUE TITLE
Would it be possible to not have the data as a retrievable property of the components?

### ISSUE THREAD

**Issue by FishmanL** [opendifferentialprivacy/whitenoise-core-python#26]
Building out an application that I'm trying to sandbox/have untrusted code operate on, and I don't want users able to pull the data in a dataset out of the components -- I could just expose a limited API but the UX is worse

**Comment by Shoeboxam** [comment]
Are you concerned about users accessing the `.value` property on components operating on private data? By default, `.value` will always return `None` if the data the component is operating on is not releasable.

For debugging purposes, it is still possible to view the private data by setting the `filter_level` to `all`. If you are concerned about users manipulating this value, it may make sense to add a compilation directive to the core library to reject this relaxed filtering level.

**Comment by Shoeboxam** [comment]
Actually, I don't see a lot of utility in adding a compilation directive to prevent an `all` filter directive- if an untrusted user can manipulate the analysis object, then the security model breaks down in other ways. For instance, the user can edit down the actual privacy usage utilized by the release mechanism, can purge the release cache, and can overwrite the graph. 

The privacy model here has the potential to work with untrusted users, due to the DSL and static checking in the validator. However, there needs to be an application layer gating access to the programming interface to work with untrusted users.

A model for this system to work with untrusted users is for the user to build their analysis, and then pass the protobuf to an external service, with user accounts and data permissions. The external service checks that the protobuf is an extension of the previous analysis (or empty graph), and uses the core library to validate. This is the general direction we are working towards for the graphical UI (but unfortunately time is finite).

**Comment by FishmanL** [comment]
Ahhh, alright, makes sense, I'll stick with the API for now then
