### ISSUE TITLE
The links to SmartNoise documentation return 404 errors

### ISSUE THREAD

**Issue by TedTed** [opendifferentialprivacy/whitenoise-core-python#71]
Hi folks,

This link: https://docs.opendp.org/en/latest/smartnoise/ is present in most of SmartNoise's top-level README.md files, and returns a 404 error. It should probably be replaced by https://docs.smartnoise.org/en/latest/api-reference/.

Lower in the README.md of this repository (and maybe others), there's also a link to https://opendp.github.io/smartnoise-core-python/, which works, but looks obsolete.

**Comment by pdurbin** [comment]
@TedTed hi! This sounds like the same problem as https://github.com/opendp/smartnoise-sdk/issues/398

The fix was this: https://github.com/opendp/smartnoise-sdk/commit/69a29e65785e45f48add39a8db6a6f7525c864bc (but it sounds like you know already that the domain changed).

If you're interested in making a pull request, please let us know!

**Comment by Shoeboxam** [comment]
Wow, time has really not been kind to these links. In a meeting with Microsoft on Monday, the consensus was to let the documentation sites for this repository lapse when we deprecate this library. See #68.

@pdurbin I think it's better we follow through with deprecating this package, rather than solicit PRs on this repository.

**Comment by raprasad** [comment]
Thanks @TedTed. (Updating the links. We plan on full deprecation this fall but also to leave the repos/older docs in place.)
